#!/bin/bash
file_out=file_out
HomeTaskFile=hometasklog
grep -E -o "[0-9]./\w{3}/[0-9]{4}:([0-9]{2}:{0,1}){2}" log | sort | uniq -c | sort -gr > $file_out
{
read line1
}<$file_out
echo $line1 > $HomeTaskFile

awk '{print $7}' log | sort | uniq -c | sort -gr > $file_out
{
read line1
}<$file_out
echo $line1 >> $HomeTaskFile

grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" log | sort | uniq -c | sort -gr >> $HomeTaskFile

awk '{print $14,$16}' log | sort | uniq | grep -E -o ".+bot" -i >> $HomeTaskFile
