# Generated by Django 3.2.9 on 2021-12-02 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of category: game, software, antivirus, etc', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='product_picture')),
                ('description', models.CharField(help_text='Enter desctiption of the product', max_length=255, verbose_name='Description')),
                ('category', models.ManyToManyField(help_text='Select product category ', max_length=255, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='KeyInstance',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'availabile'), ('n', 'not available')], default='a', help_text='Key availability', max_length=1)),
                ('value', models.CharField(help_text='Key value', max_length=255)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
