# Generated by Django 3.2.9 on 2021-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'availabile'), ('n', 'not available')], default='a', help_text='Key availability', max_length=1),
        ),
    ]
