# Generated by Django 3.2.9 on 2021-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211202_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, help_text='Product price'),
        ),
    ]
