# Generated by Django 3.2.9 on 2021-12-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='InStock',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
