# Generated by Django 3.2.9 on 2021-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211205_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='Products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Products',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
