# Generated by Django 3.2.9 on 2021-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211205_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(to='store.Product'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
