# Generated by Django 3.2.9 on 2021-12-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_user_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
