# Generated by Django 3.2.9 on 2021-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20211207_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select product category ', max_length=255, related_name='product_for_categories', to='store.Category'),
        ),
    ]
