# Generated by Django 3.2.9 on 2021-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product',
            new_name='category_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select product category ', max_length=255, to='store.Category'),
        ),
    ]
