# Generated by Django 3.2.9 on 2021-12-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20211207_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
