# Generated by Django 3.2.9 on 2021-12-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20211207_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='categorys',
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_for_product', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_product',
            field=models.ManyToManyField(related_name='product_for_ct', to='store.CategoryProduct'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_for_category', to='store.product'),
        ),
    ]
