# Generated by Django 3.2.9 on 2021-12-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20211207_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_product',
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
    ]
