# Generated by Django 3.2.9 on 2021-12-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20211207_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='products',
            new_name='product',
        ),
    ]
