# Generated by Django 3.2.9 on 2021-12-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_products_categoryproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_product',
            new_name='products',
        ),
    ]
