# Generated by Django 3.2.9 on 2021-12-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_category_product_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
    ]
