"""update knowledge area

Revision ID: 095e705c5d7a
Revises: e0f619e737b1
Create Date: 2022-01-09 16:07:57.796850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095e705c5d7a'
down_revision = 'e0f619e737b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
