"""fix coef

Revision ID: 115a58b44355
Revises: a21a50930870
Create Date: 2022-01-10 12:40:48.606897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '115a58b44355'
down_revision = 'a21a50930870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coefficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zno_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], ),
    sa.ForeignKeyConstraint(['zno_id'], ['zno_subj.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cofficient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cofficient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zno_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speciality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('coefficient', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], name='cofficient_speciality_id_fkey'),
    sa.ForeignKeyConstraint(['zno_id'], ['zno_subj.id'], name='cofficient_zno_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cofficient_pkey')
    )
    op.drop_table('coefficient')
    # ### end Alembic commands ###
