"""update knowledge area

Revision ID: e0f619e737b1
Revises: fa5fac724543
Create Date: 2022-01-09 13:41:33.761951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f619e737b1'
down_revision = 'fa5fac724543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cofficient', sa.Column('required', sa.Boolean(), nullable=True))
    op.add_column('knowledge_area', sa.Column('code', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_area', 'code')
    op.drop_column('cofficient', 'required')
    # ### end Alembic commands ###
