"""fix cf

Revision ID: e2be6b61ef0f
Revises: 98f20a131177
Create Date: 2022-01-12 22:24:04.531083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2be6b61ef0f'
down_revision = '98f20a131177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
