"""add cofficient

Revision ID: fa5fac724543
Revises: 82c99cc74c8b
Create Date: 2022-01-08 17:51:54.211832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa5fac724543'
down_revision = '82c99cc74c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speciality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('program', sa.String(length=120), nullable=True),
    sa.Column('min_rate_budget', sa.Float(), nullable=True),
    sa.Column('min_rate_pay', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['knowledge_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cofficient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zno_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('cofficient', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], ),
    sa.ForeignKeyConstraint(['zno_id'], ['zno_subj.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.Column('program', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('min_rate_budget', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_rate_pay', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['knowledge_area.id'], name='subject_area_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subject_pkey')
    )
    op.drop_table('cofficient')
    op.drop_table('speciality')
    # ### end Alembic commands ###
