"""empty message

Revision ID: 012ca5ddaa71
Revises: 584e7df82271
Create Date: 2021-12-19 14:45:44.810288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012ca5ddaa71'
down_revision = '584e7df82271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expert_ident', 'expert_uname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expert_ident', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('interview', sa.Column('zoom_link', sa.String(), nullable=True))
    op.drop_column('interview', 'candidat_answer')
    op.alter_column('question_indentif', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_indentif', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_indentif', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_indentif', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('interview', sa.Column('candidat_answer', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('interview', 'zoom_link')
    op.alter_column('expert_ident', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expert_ident', 'expert_uname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
