"""added date and time for interview

Revision ID: 10f4d36d03f0
Revises: c39c83a23a5f
Create Date: 2021-12-25 14:37:05.638257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f4d36d03f0'
down_revision = 'c39c83a23a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('interview', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview', 'time')
    op.drop_column('interview', 'date')
    # ### end Alembic commands ###
