"""change relation

Revision ID: 1273c0ebd920
Revises: 10f4d36d03f0
Create Date: 2021-12-27 18:54:45.395126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1273c0ebd920'
down_revision = '10f4d36d03f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('recrutier_id', sa.Integer(), nullable=True))
    op.drop_constraint('interview_recrutier_fkey', 'interview', type_='foreignkey')
    op.create_foreign_key(None, 'interview', 'user', ['recrutier_id'], ['id'])
    op.drop_column('interview', 'recrutier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('recrutier', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_foreign_key('interview_recrutier_fkey', 'interview', 'user', ['recrutier'], ['username'])
    op.drop_column('interview', 'recrutier_id')
    # ### end Alembic commands ###
