"""empty message

Revision ID: 694ac7b7eb05
Revises: 012ca5ddaa71
Create Date: 2021-12-19 15:12:53.023019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694ac7b7eb05'
down_revision = '012ca5ddaa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('recrutier', sa.String(length=64), nullable=True))
    op.drop_constraint('interview_interviewer_fkey', 'interview', type_='foreignkey')
    op.create_foreign_key(None, 'interview', 'user', ['recrutier'], ['username'])
    op.drop_column('interview', 'interviewer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('interviewer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.create_foreign_key('interview_interviewer_fkey', 'interview', 'user', ['interviewer'], ['username'])
    op.drop_column('interview', 'recrutier')
    # ### end Alembic commands ###
