"""some updates

Revision ID: 6ae72853fbb9
Revises: 600d207772b1
Create Date: 2021-12-16 20:41:26.948226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae72853fbb9'
down_revision = '600d207772b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_candidat_fkey', 'interview', type_='foreignkey')
    op.drop_column('interview', 'description')
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('interview', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('interview_candidat_fkey', 'interview', 'user', ['candidat'], ['username'])
    # ### end Alembic commands ###
