"""manytomay questions

Revision ID: 767548642c82
Revises: 837bf15f657e
Create Date: 2021-12-15 20:03:53.205775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767548642c82'
down_revision = '837bf15f657e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_indentif',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_indentif')
    # ### end Alembic commands ###
