"""deleted useless columl

Revision ID: 82c9c6b401c8
Revises: 1273c0ebd920
Create Date: 2021-12-29 14:13:45.519311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c9c6b401c8'
down_revision = '1273c0ebd920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
