"""users,interviews,questions

Revision ID: 837bf15f657e
Revises: 
Create Date: 2021-12-15 19:12:18.876315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837bf15f657e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('max_grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('interviewer', sa.String(length=64), nullable=True),
    sa.Column('recrutier', sa.String(length=64), nullable=True),
    sa.Column('candidat', sa.String(length=64), nullable=True),
    sa.Column('candidat_answer', sa.String(length=128), nullable=True),
    sa.Column('final_grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidat'], ['user.username'], ),
    sa.ForeignKeyConstraint(['interviewer'], ['user.username'], ),
    sa.ForeignKeyConstraint(['recrutier'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('questions')
    op.drop_table('category')
    # ### end Alembic commands ###
