"""created private key colum

Revision ID: c39c83a23a5f
Revises: cd289b6f7bcf
Create Date: 2021-12-21 20:57:06.804038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39c83a23a5f'
down_revision = 'cd289b6f7bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('private_key', sa.String(length=24), nullable=True))
    op.create_unique_constraint(None, 'user', ['private_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'private_key')
    # ### end Alembic commands ###
